pipeline {
  agent any
  parameters {
    choice(name: 'ACTION', choices: ['plan', 'apply', 'destroy'], description: 'Terraform action to perform')
  }
  stages {
    stage('prerequisite') {
            steps {
                sh '''
                echo "==== Cleaning and Cloning Repo ===="
                rm -rf /var/lib/jenkins/workspace/ec2_crud/*
                git clone https://github.com/priyanshusaineni/aws_ec2_terraform.git
                '''
            }
        }
    stage('Terraform Init') {
      steps {
        sh 'terraform init'
      }
    }
    stage('Terraform Execute') {
      steps {
        sh "terraform ${params.ACTION} --auto-approve"
      }
    }
  }
}
