pipeline {
    agent any
    environment {
        AWS_CREDS = credentials('AWS_CREDS')
    }
    parameters {
        booleanParam(name: 'TF_INIT', defaultValue: false, description: 'Run terraform init')
        booleanParam(name: 'TF_IMPORT', defaultValue: false, description: 'Run terraform import')
        string(name: 'INSTANCE_ID', defaultValue: '', description: 'EC2 instance ID for terraform import')
        booleanParam(name: 'TF_PLAN', defaultValue: false, description: 'Run terraform plan')
        booleanParam(name: 'TF_APPLY', defaultValue: false, description: 'Run terraform apply')
        booleanParam(name: 'TF_DESTROY', defaultValue: false, description: 'Run terraform destroy')
    }
    stages {
        stage('Prerequisite') {
            steps {
                sh '''
                echo "==== Cleaning and Cloning Repo ===="
                rm -rf /var/lib/jenkins/workspace/ec2_crud/*
                git clone https://github.com/priyanshusaineni/aws_ec2_terraform.git
                '''
            }
        }
        stage('Terraform Init') {
            when {
                expression { params.TF_INIT }
            }
            steps {
                sh '''
                cd aws_ec2_terraform
                terraform init
                '''
            }
        }
        stage('Terraform Import') {
            when {
                expression { params.TF_IMPORT }
            }
            steps {
                sh """
                cd aws_ec2_terraform
                terraform import 'module.ec2_instance[0].aws_instance.this[0]' $INSTANCE_ID
                terraform import 'resource.aws_ec2_instance_state.example_stop[0]' $INSTANCE_ID
                """
            }
        }
        stage('Terraform Plan') {
            when {
                expression { params.TF_PLAN }
            }
            steps {
                sh '''
                cd aws_ec2_terraform
                terraform plan
                '''
            }
        }
        stage('Terraform Apply') {
            when {
                expression { params.TF_APPLY }
            }
            steps {
                sh '''
                cd aws_ec2_terraform
                terraform apply --auto-approve
                '''
            }
        }
        stage('Terraform Destroy'){
            when {
                expression {params.TF_DESTROY}
            }
            steps{
                sh '''
                cd aws_ec2_terraform
                terraform destroy --auto-approve
                '''
            }
        }
    }
}
